<a href="https://colab.research.google.com/github/BharathReddyRamasani/AI_DS/blob/main/Numpy_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy  as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
a=np.array([[1,2,3,2],[4,5,6,4],[7,8,9,1]])
print(a.ndim)
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(d.ndim)

2
3


In [ ]:
r1=np.random.rand(4,3)
r2=np.random.random((4,3))
r3=np.random.randint((1,3))
print(r1)
print(r2)
print(r3)

[[0.98509661 0.9174148  0.11347287]
 [0.58019417 0.27836086 0.60002268]
 [0.56196513 0.55359767 0.58418113]
 [0.39399104 0.95263679 0.29258659]]
[[0.72429778 0.50974992 0.6291004 ]
 [0.79834725 0.44151468 0.13983919]
 [0.16372754 0.00345693 0.80484955]
 [0.08697345 0.48786321 0.87528624]]
[0 1]


In [ ]:
id=np.eye(3)
print(id)
id1=np.identity(3)
print(id1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
ran=np.arange(0,10,2)
print(ran)

[0 2 4 6 8]


In [ ]:
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(d)
print(d.ndim)
print("shape",d.shape)
print("size",d.size)
print("data type",d.dtype)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3
shape (2, 2, 3)
size 12
data type int64


ou are working as a Data Engineer for a smart agriculture startup that collects sensor data from multiple greenhouses.
Each greenhouse has sensors that record temperature (°C) readings at different times of the day.
You received the following data:
Your tasks are:
Create NumPy arrays
Create a 2D NumPy array named temp_data to represent the temperature readings from both greenhouses.
Print the array.
Check array properties
Print the shape, size, data type, and number of dimensions of temp_data.
Add a third greenhouse
The third greenhouse (GH3) records [21, 23, 22].
Create a new array updated_temp_data that includes all three greenhouses.
Generate supporting data
Create a zeros array (2×3) called sensor_error_flags to represent whether there were any sensor errors (0 means no error).
Create an identity matrix of size 3×3 named greenhouse_identity to uniquely identify each greenhouse.
Display all arrays
Print updated_temp_data, sensor_error_flags, and greenhouse_identity

In [ ]:
gh1=np.array([[22,25,20],[24,26,23]])
print(gh1)
print("gh1 properties")
print(gh1.shape)
print(gh1.size)
print(gh1.dtype)
print(gh1.ndim)
gh2=np.array([21,23,22])
print(gh2)
gh=np.vstack((gh1,gh2))
z=np.zeros((2,3),dtype=int)
print(z)
id=np.identity(3)
print(id)
print("results")
print(gh)
print(z)
print(id)





[[22 25 20]
 [24 26 23]]
gh1 properties
(2, 3)
6
int64
2
[21 23 22]
[[0 0 0]
 [0 0 0]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
results
[[22 25 20]
 [24 26 23]
 [21 23 22]]
[[0 0 0]
 [0 0 0]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr=np.array([[22,25,20],[24,26,23]])
print(arr[1,2])
print(arr[0,1])
print(arr[0,2])
print(arr[1:])
print(arr[ :2])
print(arr[:2:])

23
25
20
[[24 26 23]]
[[22 25 20]
 [24 26 23]]
[[22 25 20]
 [24 26 23]]


Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.
The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array
Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing

In [ ]:
shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
print("apples",shipments[0,2])
print("oranges",shipments[1,6])
print("except weekend",shipments[:,0:5])
print("weekend",shipments[:,5:7])
print("apples(wed-sat)",shipments[0,2:6])
shipments[0,5]=100
print("bonus",shipments)





apples 55
oranges 75
except weekend [[50 60 55 70 65]
 [40 45 50 60 55]]
weekend [[80 90]
 [70 75]]
apples(wed-sat) [55 70 65 80]
bonus [[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  55  70  75]]


In [ ]:
d=np.array([[1,2,3],[4,5,6],[3,4,5]])
d2=np.array([[1,2,3],[4,5,6],[5,6,7]])
print(d+d2)
print(d*d2)
print(d-d2)
print(d/d2)
print(np.dot(d,d2))
print(d*2)
print(d+2)
print(d-2)
print(d/2)

[[ 2  4  6]
 [ 8 10 12]
 [ 8 10 12]]
[[ 1  4  9]
 [16 25 36]
 [15 24 35]]
[[ 0  0  0]
 [ 0  0  0]
 [-2 -2 -2]]
[[1.         1.         1.        ]
 [1.         1.         1.        ]
 [0.6        0.66666667 0.71428571]]
[[24 30 36]
 [54 69 84]
 [44 56 68]]
[[ 2  4  6]
 [ 8 10 12]
 [ 6  8 10]]
[[3 4 5]
 [6 7 8]
 [5 6 7]]
[[-1  0  1]
 [ 2  3  4]
 [ 1  2  3]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [1.5 2.  2.5]]


In [ ]:
a=np.array([1,2,3])
b=2
print(a+b)

[3 4 5]


In [ ]:
x=45.56
y=60.9
print("1. Arithmetic ufuncs")
print(np.add(x, y))
print(np.subtract(x, y))
print(np.multiply(x, y))
print(np.divide(x, y))
print(np.power(x, y))
print(np.mod(x, y))
print("2. Exponential and Logarithmic ufuncs")
print(np.exp(x))
print(np.log(x))
print(np.log10(x))
print(np.log2(x))
print(np.expm1(x))
print(" 3. Trigonometric ufuncs")
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))
print(np.degrees(x))
print(np.radians(x))
print("🔹 4. Rounding ufuncs")
print(np.round(x))
print(np.floor(x))
print(np.ceil(x))
print(np.trunc(x))
print("🔹 5. Statistical ufuncs")
print(np.min(x))
print(np.max(x))
print(np.mean(x))
print(np.std(x))
print(np.var(x))
print(np.sum(x))
print(np.prod(x))
print("🔹 6. Logical ufuncs")
print(np.logical_and(x, y))
print(np.logical_or(x, y))
print(np.logical_not(x))
print(np.logical_xor(x, y))
print("🔹 7. Comparison ufuncs")
print(np.greater(x, y))
print(np.less(x, y))
print(np.equal(x, y))
print(np.not_equal(x, y))
print(np.greater_equal(x, y))
print(np.less_equal(x, y))
print("🔹 8. Bitwise ufuncs")
a=3
b=5
print(np.bitwise_and(a, b))
print(np.bitwise_or(a, b))
print(np.bitwise_xor(a, b))
print(np.invert(a))


1. Arithmetic ufuncs
106.46000000000001
-15.339999999999996
2774.6040000000003
0.7481116584564861
1.0180011492544623e+101
45.56
2. Exponential and Logarithmic ufuncs
6.115846765822929e+19
3.8190301385789813
1.6585837154070628
5.509695841933387
6.1158467658229285e+19
 3. Trigonometric ufuncs
0.9999761500651883
-0.006906468041205652
-144.78835550951507
nan
nan
1.5488507723818314
2610.3957146160305
0.7951720072086166
🔹 4. Rounding ufuncs
46.0
45.0
46.0
45.0
🔹 5. Statistical ufuncs
45.56
45.56
45.56
0.0
0.0
45.56
45.56
🔹 6. Logical ufuncs
True
True
False
False
🔹 7. Comparison ufuncs
False
True
False
True
False
True
🔹 8. Bitwise ufuncs
1
7
6
-4


/tmp/ipython-input-4086705235.py:20: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(x))
/tmp/ipython-input-4086705235.py:21: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(x))


In [ ]:
import numpy as np
farmA = np.array([[12,13.5,11.8],[10.2,11,10.8],[14.1,14.5,13.9],[9.5,10.1,9.8]])
farmB = np.array([[8.5,9,8.9],[11.2,11.9,12.1],[13,12.7,13.4],[7.8,8,7.9]])
farmC = np.array([[15,15.5,15.2],[9.9,10.3,10],[12.5,12.8,12.6],[11,10.7,11.2]])

production_all = np.stack([farmA,farmB,farmC])
print(production_all)
print(production_all.shape, production_all.size, production_all.dtype, production_all.ndim)

# Aggregations
total_per_farm = production_all.sum((1,2))
mean_per_farm = production_all.mean((1,2))
std_per_farm  = production_all.std((1,2))
print("total_per_farm, mean_per_farm, std_per_farm",total_per_farm, mean_per_farm, std_per_farm)

# Weighted
hour_weights = np.array([0.5,1,0.75])
weighted_per_panel = production_all.dot(hour_weights)
print("weighted_per_panel",weighted_per_panel)

# Calibration
production_all[1] += 0.5

# Normalize
pf_mean = production_all.mean((1,2))
pf_std  = production_all.std((1,2))
norm = (production_all - pf_mean)/pf_std

# Ufuncs
expv, logv, sinv = np.exp(norm), np.log(np.abs(norm)+1), np.sin(norm)

# Logical masks
high_output = production_all > 20
print(np.any(high_output))

# Bitwise
alerts = np.tile(np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]),(3,1,1))
bit_inv = np.bitwise_not(alerts)

# Panel totals & maintenance
panel_totals = production_all.sum(2)
needs_maint = np.any(panel_totals<40,1)
print(panel_totals, needs_maint)

# KPIs
overall_total = production_all.sum()
peak_idx = np.unravel_index(np.argmax(production_all), production_all.shape)
avg_panel = panel_totals.mean(0)
print(overall_total, production_all[peak_idx], peak_idx, avg_panel)


[[[12.  13.5 11.8]
  [10.2 11.  10.8]
  [14.1 14.5 13.9]
  [ 9.5 10.1  9.8]]

 [[ 8.5  9.   8.9]
  [11.2 11.9 12.1]
  [13.  12.7 13.4]
  [ 7.8  8.   7.9]]

 [[15.  15.5 15.2]
  [ 9.9 10.3 10. ]
  [12.5 12.8 12.6]
  [11.  10.7 11.2]]]
(3, 4, 3) 36 float64 3
total_per_farm, mean_per_farm, std_per_farm [141.2 124.4 146.7] [11.76666667 10.36666667 12.225     ] [1.73893326 2.10963399 1.9740504 ]
weighted_per_panel [[28.35  24.2   31.975 22.2  ]
 [19.925 26.575 29.25  17.825]
 [34.4   22.75  28.5   24.6  ]]
False
[[37.3 32.  42.5 29.4]
 [27.9 36.7 40.6 25.2]
 [45.7 30.2 37.9 32.9]] [ True  True  True]
418.3 15.5 (np.int64(2), np.int64(0), np.int64(1)) [36.96666667 32.96666667 40.33333333 29.16666667]


In [ ]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2,2,3)

print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
arr=np.array([1,2,3,4,5,6])
print(np.array_split(arr,7))

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64)]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
x=arr.copy()
arr[3]=100
print(x)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[  1   2   3 100   5   6   7   8   9  10  11  12]


TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.


In [ ]:
import numpy as np

arr1 = np.arange(10, 51)
arr2 = np.random.rand(3, 3)

print("arr1:", arr1)
print("arr2:\n", arr2)
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Data type:", arr2.dtype)

arr = np.array([1, 2, 3, 4, 5])
arr_add = arr + 5
print("After adding 5:", arr_add)

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = a * b
print("Element-wise multiplication:\n", result)

arr3 = np.arange(1, 26).reshape(5, 5)
first_row = arr3[0]
last_col = arr3[:, -1]
subarray = arr3[:3, :2]

print("First row:", first_row)
print("Last column:", last_col)
print("Subarray (first 3 rows, first 2 cols):\n", subarray)


arr4 = np.random.randint(10, 101, 10)
print("Array:", arr4)
print("Max:", arr4.max())
print("Min:", arr4.min())
print("Mean:", arr4.mean())
print("Standard Deviation:", arr4.std())

arr5=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr6=arr5.reshape(3,4)
print("arr6:\n",arr6)

arr7=np.ones((3,3))
print("arr7",arr7)
arr8=np.array([1,2,3])
arr9=arr7+arr8
print("arr9:\n",arr9)


arr10 = np.random.randint(1, 51,20)
div_by_5 = arr10[arr10 % 5 == 0]
print("Array:", arr10)
print("Elements divisible by 5:", div_by_5)

arr11=np.array([[1,2],[3,4]])
arr12=np.array([[5,6],[7,8]])
result=np.dot(arr11,arr12)
print("result:\n",result)

arr13 = np.arange(1, 17).reshape(4, 4)
diag_elements = arr13[np.arange(4), np.arange(4)]
print("Array:\n", arr13)
print("Diagonal elements:", diag_elements)




arr1: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
arr2:
 [[0.39680622 0.85176385 0.67990853]
 [0.27558326 0.15432527 0.18283312]
 [0.62204229 0.25762573 0.05738959]]
Shape: (3, 3)
Size: 9
Data type: float64
After adding 5: [ 6  7  8  9 10]
Element-wise multiplication:
 [[ 5 12]
 [21 32]]
First row: [1 2 3 4 5]
Last column: [ 5 10 15 20 25]
Subarray (first 3 rows, first 2 cols):
 [[ 1  2]
 [ 6  7]
 [11 12]]
Array: [ 73  63  16  61  64 100  62  59  39  56]
Max: 100
Min: 16
Mean: 59.3
Standard Deviation: 20.464847910502538
arr6:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
arr7 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr9:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
Array: [26  7 40 25 30 15  3 19 29 14 10 44 19 41 30  1  5 31  8 44]
Elements divisible by 5: [40 25 30 15 10 30  5]
result:
 [[19 22]
 [43 50]]
Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Diagonal elements: [ 1  6 11 16]
